# Generated by Django 5.2.8 on 2026-01-07 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalPetPassport',
            fields=[
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='passport', serialize=False, to='pet.pet')),
                ('vet_notes', models.TextField(blank=True, help_text='General veterinary notes.')),
            ],
        ),
        migrations.CreateModel(
            name='PetDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='pet_documents/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='pet.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('VET', 'Veterinary Appointment'), ('FEED', 'Feeding Time'), ('OTH', 'Other')], default='OTH', max_length=4)),
                ('reminder_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='pet.pet')),
            ],
        ),
    ]
