# Generated by Django 6.0.1 on 2026-01-09 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_digitalpetpassport_petdocument_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('VACC', 'Vaccination'), ('VET', 'Veterinary Appointment'), ('FEED', 'Feeding Time'), ('OTH', 'Other')], default='OTH', max_length=4),
        ),
        migrations.CreateModel(
            name='DailyCareLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(help_text='Date of the activity')),
                ('log_time', models.TimeField(help_text='Time of the activity')),
                ('activity_type', models.CharField(choices=[('FEED', 'Feeding'), ('MED', 'Medication'), ('WALK', 'Walk/Exercise'), ('OTH', 'Other')], default='OTH', max_length=4)),
                ('description', models.TextField(help_text='Description of the activity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_logs', to='pet.pet')),
            ],
            options={
                'ordering': ['-log_date', '-log_time'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(help_text='Name of the vaccine (e.g., Rabies, Distemper)', max_length=100)),
                ('vaccination_date', models.DateField(help_text='Date when the vaccine was administered')),
                ('next_due_date', models.DateField(blank=True, help_text='Next due date for this vaccine', null=True)),
                ('veterinarian_name', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='pet.pet')),
            ],
            options={
                'ordering': ['-vaccination_date'],
            },
        ),
        migrations.CreateModel(
            name='VeterinaryAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(help_text='Date and time of the appointment')),
                ('veterinarian_name', models.CharField(max_length=100)),
                ('clinic_name', models.CharField(blank=True, max_length=200)),
                ('reason', models.CharField(help_text='Reason for the visit', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the appointment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vet_appointments', to='pet.pet')),
            ],
            options={
                'ordering': ['-appointment_date'],
            },
        ),
    ]
