# Generated by Django 5.2.8 on 2026-01-10 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_remove_dayofweek_activity_feeding_medication_walk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pet_documents/')),
                ('title', models.CharField(help_text='Например: Ветпаспорт, Анализ крови, Вакцинация', max_length=150)),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('vaccination', 'Vaccination'), ('analysis', 'Medical Analysis'), ('insurance', 'Insurance'), ('other', 'Other')], default='other', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='pet.pet')),
            ],
            options={
                'verbose_name': 'Pet Document',
                'verbose_name_plural': 'Pet Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
